/**
 * Layerinfinite — hooks/useAgentApiKey.ts
 * ══════════════════════════════════════════════════════════════
 * Provides the agent API key for calls to /v1/* agent routes.
 *
 * API CALL RULE: All calls to /v1/* MUST use the agent API key from localStorage.
 * NEVER use supabase.auth.getSession() token for agent routes.
 * The Supabase JWT is only valid for dashboard auth (user_profiles, etc.).
 * Agent API routes use SHA-256-hashed layerinfinite_XXXX keys in dim_agents.
 *
 * Key storage: localStorage key 'layerinfinite_api_key'
 * Key format:  layerinfinite_ + exactly 32 lowercase hex chars [0-9a-f]
 * (Matches the format generated by api-keys.ts: generateApiKey())
 *
 * On 401/403 response from any agent API call:
 *   - Clear the stale key from localStorage
 *   - Redirect to /onboarding?step=2&reason=expired
 *   - Show toast: "API key expired or missing. Please regenerate."
 * ══════════════════════════════════════════════════════════════
 */

import { useCallback, useEffect, useMemo, useState } from 'react';

// Matches the output of generateApiKey() in api/routes/auth/api-keys.ts:
//   `layerinfinite_${hex}` where hex is 16 random bytes → 32 lowercase hex chars.
// Condition verified: api-keys.ts uses new Uint8Array(16) + b.toString(16).padStart(2,'0')
// → 32 chars of [0-9a-f]. This regex must match that exact output.
const API_KEY_REGEX = /^layerinfinite_[0-9a-f]{32}$/;

export const AGENT_API_KEY_STORAGE_KEY = 'layerinfinite_api_key';

export interface AgentApiKeyResult {
  /** The validated API key, or null if missing/invalid */
  apiKey: string | null;
  /** True if the key is present and passes format validation */
  isValid: boolean;
  /** Error message when key is missing or invalid format */
  error: string | null;
  /** Call this after storing a new key to refresh the hook state */
  refresh: () => void;
  /**
   * Call this when a /v1/* request returns 401 or 403.
   * Clears the key and redirects to onboarding step 2.
   */
  handleAuthFailure: () => void;
}

function readAndValidateKey(): { key: string | null; error: string | null } {
  try {
    const stored = localStorage.getItem(AGENT_API_KEY_STORAGE_KEY) ?? '';
    if (!stored) {
      return { key: null, error: 'No API key found. Create one in Settings → API Keys.' };
    }
    if (!API_KEY_REGEX.test(stored)) {
      // Key is present but malformed — clear it to avoid a silent loop
      localStorage.removeItem(AGENT_API_KEY_STORAGE_KEY);
      return { key: null, error: 'Stored API key has an invalid format. Please regenerate.' };
    }
    return { key: stored, error: null };
  } catch {
    // localStorage unavailable (private mode, etc.)
    return { key: null, error: 'Unable to read API key from storage.' };
  }
}

export function useAgentApiKey(): AgentApiKeyResult {
  const [tick, setTick] = useState(0);

  // ← KEY FIX: useMemo(fn, [tick]) ensures readAndValidateKey()
  // re-runs every time refresh() is called or tick changes.
  // Without this, React reuses the stale result from the first render.
  const { key, error } = useMemo(() => readAndValidateKey(), [tick]);

  useEffect(() => {
    const handler = (e: StorageEvent) => {
      if (e.key === AGENT_API_KEY_STORAGE_KEY) {
        setTick((v) => v + 1);
      }
    };
    window.addEventListener('storage', handler);
    return () => window.removeEventListener('storage', handler);
  }, []);

  const refresh = useCallback(() => {
    setTick((v) => v + 1);
  }, []);

  const handleAuthFailure = useCallback(() => {
    try {
      localStorage.removeItem(AGENT_API_KEY_STORAGE_KEY);
    } catch {
      // ignore
    }
    // Redirect to onboarding step 2 so the user can regenerate their key
    window.location.href = '/onboarding?step=2&reason=expired';
  }, []);

  return {
    apiKey: key,
    isValid: key !== null,
    error,
    refresh,
    handleAuthFailure,
  };
}
